### ISSUE TITLE
Полноэкранный просмотр фотографий на мобилах

### ISSUE THREAD

**Issue by gallyamb** [urfu-2016/team3#112]
На мобильных устройствах даже свайп по фото переключает на следующее фото.

**Comment by LeMarck** [comment]
А что плохого в том, что свайп переключает фото? Он вроде как для этого и сделан, чтобы свайпом листать фотки.

**Comment by gallyamb** [comment]
Я покажу пример в вс. Описать текстом довольно трудно.
