### ISSUE TITLE
Email verification

### ISSUE THREAD

**Issue by gallyamb** [urfu-2016/team3#68]

**Comment by LeMarck** [comment]
https://www.npmjs.com/package/mongoose-validators

**Comment by gallyamb** [comment]
Классная штука. Только в задаче нужно проверить, что этот email действительно существует и принадлежит пользователю. То есть сделать подтверждение email/учетной записи. Нужно было, конечно, сразу это прописать)

**Comment by LeMarck** [comment]
Сам тупанул и вместо верификации подумал про валидацию

**Comment by LeMarck** [comment]
Можно при регистрации выставлять пользователю в поле верификации false и выслать письмо с просьбой подтверждения и ссылкой в ней. Пользователь перешёл по ссылке - верификация true

**Comment by gallyamb** [comment]
https://www.npmjs.com/package/email-verification
Выглядит удобно
