### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by gallyamb** [urfu-2016/team3#79]
Что думаете насчёт включения поддержки markdown разметки в описаниях квеста/фото? Кажется, что сделать не сложно. Будет дополнительная фича

**Comment by gallyamb** [comment]
https://github.com/chjj/marked

**Comment by IrinaSed** [comment]
Так то можно, но нужно сначала сделать обязательные таски

**Comment by gallyamb** [comment]
Естественно, обязательные в первую очередь)
