### ISSUE TITLE
Комментарии может создавать любой

### ISSUE THREAD

**Issue by gallyamb** [urfu-2016/team3#99]
Сейчас комменты может попытаться создать любой пользователь (авторизованный/неавторизованный). Но при это если комментит неавторизованный, приложение падает.
Нужно либо запретить комментить неавторизованным, либо обрабатывать этот случай.

Как по мне, то первый вариант проще и лучше

**Comment by LeMarck** [comment]
Можно просто не показывать форму для ввода комментария неавторизованному пользователю

**Comment by gallyamb** [comment]
Это не решение. Любой все равно может послать POST запрос из curl. Дополнительная валидация/сокрытие форм и пр. на фронте это, конечно же, плюс, но в конечном счете вся логика приложения должна быть на сервере.

**Comment by LeMarck** [comment]
Я думаю, что эту задачу можно закрывать
